apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: conm-system
spec:
  selector:
    matchLabels:
      app: nginx
      tier: test-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        tier: test-deployment
    spec:
      nodeSelector:
        nginx: true
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
