apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  namespace: conm-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      nodeSelector:
        nginx: "true"

      containers:
        - name: my-app
          image: nginx
